### PR TITLE
made fixes so it works for new quarter

### PR DESCRIPTION
**Pull request by eduardo-escoto**

### CODE REVIEW

**Comment by eduardo-escoto** [comment]
Aslo included submit script that can be ran from within notebook. The autograding script should run and work so Yuxiao can begin grading :)

**Comment by syoh** [comment]
Hey @eduardo-exists and @ykharitonova 

Thanks for this code. I am using your pull request commit to upload stuff to codepost for my class.

I have some suggestions:

- [`nbconvert`](https://nbconvert.readthedocs.io/en/latest/usage.html#notebook-and-preprocessors) can ignore error: e.g.,  in [`runGrading.sh`](https://github.com/ucsb-int5/codepost-grader/blob/13c084eb070442119ecc1bf66cb740aaf591c51e/runGrading.sh#L12)
    ```
    jupyter nbconvert --ExecutePreprocessor.allow_errors=True --to notebook --inplace --execute $notebook 2>&1 | tee -a log.txt;
    ```
    (I just noticed that the documentation says `--allow-errors` works also)

- Also, if this [gofer-grader](https://github.com/ucsb-pstat/Gofer-Grader.git) is installed, a [grading script like this](https://gist.github.com/syoh/d0bfe48aad67cd5117911c0eb781254f) will generate a report like this: [result.txt](https://github.com/ucsb-int5/codepost-grader/files/3777552/result.txt). (I merged some existing code in other branches of Gofer-Grader)  
    I suppose your [`upload_tests copy.py`](https://github.com/ucsb-int5/codepost-grader/blob/13c084eb070442119ecc1bf66cb740aaf591c51e/upload_tests%20copy.py) can be modified, but it would be easier if you can take a look. 

Thanks!

**Comment by eduardo-escoto** [comment]
Thanks Professor Oh! Will Take a look at all of this right now!

**Comment by eduardo-escoto** [comment]
Made the changes using professor Oh's suggestions and the gofer grader! Closing this pull request to make a new one.

Thank you @syoh for your help!

**Pull request closed without merging**
